language: node_js
node_js: node
deploy:
  provider: heroku
  api_key:
    secure: z3t+JCo9sZg70cBT8fWC3K4egViyUMRsXZ9JptG7YH5/gLFI8cYYjoa3R9iTihV4nzGFsCzLyh8cXuwKUogOGwze0Eg1wQY/BmZ8KKRecnhLi3tm9e+reymSYU9DVwOPlB4wC4tqGjNS4MmhnD69ZyGpqoUG/FuJ4mA9AT+icY5xZTMqHsjjNEQaZscmmANsQqLNN2nIMwEtDTvI46/bpheeUExdCBSxpUWE5DdoC0TAsNrnYR0kGpS7KoQd+FoR7sJj6p24+t19DoRC7zvnLBuNcRgNsEGYr4p9zxu7DmHqO9Wiqv6pzVd17i3mN03xIGvtw0RBhVm8sgtA+MWvdCFrW9rKE0/S3c0F8Pb6Y7fQYVHejWmzlMwRUtZRXJCkLYScoxkw1QFh98pCwCU945JjkKrH85FcayTKWgrOQ4tbQtwqEInf5ETqKmz4I735405xh6GxQkm2+DegRrIJA5sA8ywQZeH9ZAN6wqaOXGb9p18XAigrJba7tCKlqoozLUEf23Zrg9e9yXOkYmQ9G8E3OekoE7lmlNvkK3sMVgrCZNzmggI8X4z5Me5T9nbd37Of6PjqPWWzxrPDllKVyJWe9jSbu1UMc/UXM0ol+5JsR2gHL4rSQaW/VevubxrkKRt2tsFZ3Z1T3wX4xTSojor+jyZ+EkVBvf9iLXl6hTI=
  app: gentle-wave-70580
  on:
    repo: wshuang6/blog-app-mongoose-challenge-solution
